### ISSUE TITLE
Expose error recording rules to prometheus

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/installer-operator#1]
We can use loki ruler to record error log metrics，and display them in a observability dashboard on KubeGems.

> This is an  example.

First ,we need to add a recording rules on loki. like this.

```
name: ErrorLogs
interval: 1m
rules:
  - record: errorlogs:rate1m
    expr: |
      sum(
        rate({cluster="xxx"}[1m])
      ) by (tenant,namespace,project,environment)
    labels:
      tenant: "xxxx"
      environment: "xxxx"
      namespace: "xxxx"
      project: "xxxx"
```
This query (expr) will be executed every 1 minute (interval), the result of which will be stored in the metric name we have defined (record). This metric named `errorlogs:rate1m` can now be sent to Prometheus, where it will be stored just like any other metric.

With recording rules,  can run these metric queries continually on an interval, and have the resulting metrics written to a Prometheus-compatible **remote-write** endpoint. They produce Prometheus metrics from log entries. like this

```
ruler:  
  remote_write:
    enabled: true
    client:
      url: http://gemcloud-monitoring-system:9090/api/v1/write
```
